USERNAME = 'example@gmail.com'
PASSWORD = 'user_password'
SENDER_EMAIL = 'example@gmail.com'
GMAIL_IMAP = 'imap.gmail.com'
FOLDER_TO_SCAN = 'INBOX'
SUBJECT_TO_MATCH = 'TESTING'
DESTINATION_FOLDER = 'TMP'
